complexity:
  active: true
  TooManyFunctions:
    active: true
    excludes: '**/test/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt'
    thresholdInFiles: 50
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20
    ignoreDeprecated: true
    ignorePrivate: true
    ignoreOverridden: true
